GET http://localhost:9572/

###

GET http://localhost:9572/hungary

###

GET http://localhost:9572/slovakia

###

GET http://localhost:9572/austria

###

GET http://localhost:9572/slovenia

###

GET http://localhost:9572/us
